### ISSUE TITLE
为什么我运行entrance.py，就提示报错的？

### ISSUE THREAD

**Issue by romantico21** [xuhaixiang1993/Python3-requests#2]
C:\Users\hfwl\AppData\Local\Programs\Python\Python37\python.exe D:/Python3-requests-master/entrance.py
Traceback (most recent call last):
  File "D:/Python3-requests-master/entrance.py", line 5, in <module>
    from TestCase.testPost import TestPost
  File "D:\Python3-requests-master\TestCase\testPost.py", line 3, in <module>
    from Common.base import Base
  File "D:\Python3-requests-master\Common\base.py", line 8, in <module>
    from Logs.log import log1
  File "D:\Python3-requests-master\Logs\log.py", line 54, in <module>
    log1 = get_log("requests")
  File "D:\Python3-requests-master\Logs\log.py", line 27, in get_log
    fh = logging.FileHandler(all_log_name)
  File "C:\Users\hfwl\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 1092, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\Users\hfwl\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 1121, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Python3-requests-master\\Logs\\All_Logs\\201905162116.log'

Process finished with exit code 1

求大神帮忙指导，谢谢

**Comment by xuhaixiang1993** [comment]
有一个案例是为了测试，测试报告能把报错的用例统计进去。所以有一个报错是正常。另外就是其他正常的示例，是需要使用自己的信息的。比如第一个post示例中的要使用自己的githu 账号密码。发送邮件中的配置也要使用自己的邮箱和授权码。

**Comment by romantico21** [comment]
好的，我试试

**Comment by romantico21** [comment]
大神有没有微信、QQ的，在你有空的时间指导指导我这个菜鸟的，谢谢

**Comment by romantico21** [comment]
为啥会提示生成不了LOG文件呢？还是跟之前一样的问题，我也配置url、邮件授权码、邮箱地址、密码等，但是还是提示：
C:\Users\hfwl\AppData\Local\Programs\Python\Python37\python.exe D:/Python3-requests-master/entrance.py
Traceback (most recent call last):
  File "D:/Python3-requests-master/entrance.py", line 7, in <module>
    from TestCase.testGet import TestGet
  File "D:\Python3-requests-master\TestCase\testGet.py", line 3, in <module>
    from Common.base import Base
  File "D:\Python3-requests-master\Common\base.py", line 8, in <module>
    from Logs.log import log1
  File "D:\Python3-requests-master\Logs\log.py", line 54, in <module>
    log1 = get_log("requests")
  File "D:\Python3-requests-master\Logs\log.py", line 27, in get_log
    fh = logging.FileHandler(all_log_name)
  File "C:\Users\hfwl\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 1092, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\Users\hfwl\AppData\Local\Programs\Python\Python37\lib\logging\__init__.py", line 1121, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Python3-requests-master\\Logs\\All_Logs\\201905201629.log'

Process finished with exit code 1

**Comment by xuhaixiang1993** [comment]
Logs文件夹下是不是没有All_Logs文件




| |
徐海祥
|
|
邮箱：kael_xu@163.com
|

签名由 网易邮箱大师 定制

在2019年05月20日 16:48，romantico21 写道：

为啥会提示生成不了LOG文件呢？还是跟之前一样的问题，我也配置url、邮件授权码、邮箱地址、密码等，但是还是提示：
C:\Users\hfwl\AppData\Local\Programs\Python\Python37\python.exe D:/Python3-requests-master/entrance.py
Traceback (most recent call last):
File "D:/Python3-requests-master/entrance.py", line 7, in
from TestCase.testGet import TestGet
File "D:\Python3-requests-master\TestCase\testGet.py", line 3, in
from Common.base import Base
File "D:\Python3-requests-master\Common\base.py", line 8, in
from Logs.log import log1
File "D:\Python3-requests-master\Logs\log.py", line 54, in
log1 = get_log("requests")
File "D:\Python3-requests-master\Logs\log.py", line 27, in get_log
fh = logging.FileHandler(all_log_name)
File "C:\Users\hfwl\AppData\Local\Programs\Python\Python37\lib\logging_init_.py", line 1092, in init
StreamHandler.init(self, self.open())
File "C:\Users\hfwl\AppData\Local\Programs\Python\Python37\lib\logging_init.py", line 1121, in _open
return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'D:\Python3-requests-master\Logs\All_Logs\201905201629.log'

Process finished with exit code 1

**Comment by xuhaixiang1993** [comment]
在上传的时候，这两个存日志的文件夹是空的，上传时空的文件夹貌似不会被创建，看下是不是少两个存日志的文件夹




| |
徐海祥
|
|
邮箱：kael_xu@163.com
|

签名由 网易邮箱大师 定制

在2019年05月20日 18:49，xuhaixiang1993 写道：
Logs文件夹下是不是没有All_Logs文件




| |
徐海祥
|
|
邮箱：kael_xu@163.com
|

签名由 网易邮箱大师 定制

在2019年05月20日 16:48，romantico21 写道：

为啥会提示生成不了LOG文件呢？还是跟之前一样的问题，我也配置url、邮件授权码、邮箱地址、密码等，但是还是提示：
C:\Users\hfwl\AppData\Local\Programs\Python\Python37\python.exe D:/Python3-requests-master/entrance.py
Traceback (most recent call last):
File "D:/Python3-requests-master/entrance.py", line 7, in
from TestCase.testGet import TestGet
File "D:\Python3-requests-master\TestCase\testGet.py", line 3, in
from Common.base import Base
File "D:\Python3-requests-master\Common\base.py", line 8, in
from Logs.log import log1
File "D:\Python3-requests-master\Logs\log.py", line 54, in
log1 = get_log("requests")
File "D:\Python3-requests-master\Logs\log.py", line 27, in get_log
fh = logging.FileHandler(all_log_name)
File "C:\Users\hfwl\AppData\Local\Programs\Python\Python37\lib\logging_init_.py", line 1092, in init
StreamHandler.init(self, self.open())
File "C:\Users\hfwl\AppData\Local\Programs\Python\Python37\lib\logging_init.py", line 1121, in _open
return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'D:\Python3-requests-master\Logs\All_Logs\201905201629.log'

Process finished with exit code 1

**Comment by romantico21** [comment]
果然是，我之前的文件夹加错了，加多了一层目录，非常感谢指导
